/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background:       '#0A0A0A',
        'surface-01':     '#141414',
        'surface-02':     '#1E1E1E',
        'surface-03':     '#2A2A2A',
        border:           '#2E2E2E',
        'border-subtle':  '#1F1F1F',
        accent:           '#C8FF00',
        'accent-dim':     '#A0CC00',
        'accent-muted':   '#C8FF0020',
        'accent-glow':    '#C8FF0040',
        'text-primary':   '#FFFFFF',
        'text-secondary': '#A0A0A0',
        'text-tertiary':  '#5C5C5C',
        'text-on-accent': '#0A0A0A',
        success:          '#C8FF00',
        warning:          '#FFB800',
        danger:           '#FF4444',
        info:             '#4D9EFF',
        overlay:          '#00000080',
        'overlay-heavy':  '#000000CC',
      },
      fontFamily: {
        bebas:            ['BebasNeue_400Regular'],
        dm:               ['DMSans_400Regular'],
        'dm-medium':      ['DMSans_500Medium'],
        'dm-semi':        ['DMSans_600SemiBold'],
        'dm-bold':        ['DMSans_700Bold'],
        'dm-mono':        ['DMMono_400Regular'],
        'dm-mono-medium': ['DMMono_500Medium'],
      },
      borderRadius: {
        xs:   4,
        sm:   8,
        md:   12,
        lg:   16,
        xl:   24,
        full: 9999,
      },
      spacing: {
        '18': 72,
        '22': 88,
      },
      fontSize: {
        'd-xl':  64,
        'd-lg':  48,
        'd-md':  36,
        'd-sm':  28,
        'h-lg':  22,
        'h-md':  18,
        'h-sm':  16,
        'b-lg':  16,
        'b-md':  14,
        'b-sm':  12,
        'l-lg':  14,
        'l-md':  12,
        'l-sm':  10,
        'm-lg':  20,
        'm-md':  14,
        'm-sm':  12,
      },
    },
  },
  plugins: [],
};
